title: Joshnee Kim Awesome Title
author: Joshnee Kim Handsome
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  this Joshnee Kim's awesome description. He is very handsome.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
